# Prevents WIP PRs from being merged
name: Sanity check
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
      - unlabeled

jobs:
  pr_wip_check:
    runs-on: ubuntu-latest
    name: WIP Check
    steps:
    - name: Setup build caching to improve performance
      uses: satackey/action-docker-layer-caching@v0.0.8

    - name: WIP Check
      uses: ParanoidBeing/action-wip-blocker@v0.1.1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BLOCK_LIST: "WIP|work in progress"
